// USUARIO
export const OBTENER_USUARIO: string = 'OBTENER_USUARIO';
export const LOGIN_ERROR: string = 'LOGIN_ERROR';
export const CERRAR_SESION: string = 'CERRAR_SESION';

// CONFIGURACION
export const OBTENER_CONFIGURACION: string = 'OBTENER_CONFIGURACION';
