export * from './compress.images';
export * from './consts';
export * from './control.decimal';
export * from './delete.info';
export * from './handleError';
export * from './meses';
export * from './toBase64';
export * from './validarFotoPerfil';
export * from './getRandomColor';
